AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  randomRestaurant:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::889933016018:role/service-role/lambda_test01'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{location}'
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: '/{location}/{cuisine}'
            Method: GET
