---
swagger: "2.0"
info:
  version: "2018-08-02T14:22:03Z"
  title: "Random Restaurant Selector"
host: "9x6wmuoxc6.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /home:
    get:
      consumes:
      - "application/json"
      produces:
      - "text/html"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /{location}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "location"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
        400:
          description: "400 response"
  /{location}/{cuisine}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "cuisine"
        in: "path"
        required: true
        type: "string"
      - name: "location"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
        400:
          description: "400 response"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
